import Link from "next/link";
import { notFound } from "next/navigation";
import { AppHeader } from "@/components/AppHeader";
import { BottomNav } from "@/components/BottomNav";
import { TripOfflinePackV9 } from "@/components/TripOfflinePackV9";
import { requireVerifiedUser } from "@/lib/supabase/auth";

export default async function OfflinePackPage({params}:{params:Promise<{id:string}>}){const{id}=await params;const{supabase}=await requireVerifiedUser(`/trips/${id}/offline-pack`);const[{data:trip},{data:transports},{data:bookings},{data:docs}]=await Promise.all([
  supabase.from("trips").select("id,title,start_date,end_date,cities,trip_days(id,trip_date,title,notes,activities(id,title,activity_type,start_time,duration_minutes,location_name,maps_url,notes,status))").eq("id",id).single(),
  supabase.from("transport_segments").select("id,day_id,mode,operator,service_name,origin,destination,departure_time,arrival_time,booking_reference,seat,notes").eq("trip_id",id).order("sort_order"),
  supabase.from("bookings").select("id,booking_type,title,provider,reference_code,start_at,end_at,confirmation_url,notes,details").eq("trip_id",id).neq("booking_type","document"),
  supabase.from("bookings").select("id,title,provider,reference_code,confirmation_url,notes,details").eq("trip_id",id).eq("booking_type","document")
]);if(!trip)notFound();const pack={trip:{id:trip.id,title:trip.title,start_date:trip.start_date,end_date:trip.end_date,cities:trip.cities},days:trip.trip_days||[],transports:transports||[],bookings:bookings||[],documents:(docs||[]).map((d:any)=>({title:d.title,provider:d.provider,reference_code:d.reference_code,confirmation_url:d.confirmation_url,notes:d.notes,file_name:d.details?.file_name||null})),emergency:{police:"110",ambulance_fire:"119",jnto:"050-3816-2787",thai_embassy_tokyo:"03-5789-2433"}};return <main className="shell"><div className="container"><AppHeader/><div className="planner-topbar"><Link href={`/trips/${id}/more`} className="back-link">‹ More</Link><span className="planner-counter">V9.3 Offline Trip Pack</span></div><section className="planner-hero offline-v9-hero"><div><span className="eyebrow">TRAVEL WITHOUT SIGNAL</span><h1>📴 Offline Trip Pack</h1><p>{trip.title} · เก็บข้อมูลสำคัญก่อนออกจากโรงแรมหรือขึ้นพื้นที่สัญญาณอ่อน</p></div><Link className="btn btn-secondary" href="/offline">เปิด Offline View</Link></section><TripOfflinePackV9 tripId={id} tripTitle={trip.title||"Trip"} pack={pack}/>
<section className="section"><div className="section-head"><h2>ข้อมูลที่จะเก็บ</h2></div><div className="quick-actions v9-offline-cards"><div className="quick-action"><span>🗓️</span><strong>Day Plans</strong><small>{trip.trip_days?.length||0} วัน</small></div><div className="quick-action"><span>🚆</span><strong>Transport</strong><small>{transports?.length||0} ช่วง</small></div><div className="quick-action"><span>🎫</span><strong>Bookings</strong><small>{bookings?.length||0} รายการ</small></div><div className="quick-action"><span>📂</span><strong>Document refs</strong><small>{docs?.length||0} รายการ</small></div><div className="quick-action"><span>🆘</span><strong>Emergency</strong><small>110 · 119 · JNTO</small></div></div></section>
<section className="notice"><span>🔐</span><div><strong>ไฟล์จริงยังคงอยู่ใน Private Storage</strong><p>Offline Pack เก็บ metadata/ลิงก์อ้างอิงและแผนที่จำเป็น ไม่ดาวน์โหลดไฟล์ Passport/Voucher ทั้งหมดลงเครื่องโดยอัตโนมัติ เพื่อลดความเสี่ยงด้านข้อมูลส่วนตัว</p></div></section>
</div><BottomNav active="/more" tripId={id} /></main>}
