import Link from "next/link";
import { notFound } from "next/navigation";
import { AppHeader } from "@/components/AppHeader";
import { BottomNav } from "@/components/BottomNav";
import { DrivingChecklist } from "@/components/DrivingChecklist";
import { requireVerifiedUser } from "@/lib/supabase/auth";
import { mapsDirectionsUrl } from "@/lib/v8";

function detail(details:Record<string,unknown>|null,key:string){const v=details?.[key];return typeof v==="string"||typeof v==="number"||typeof v==="boolean"?String(v):"";}
export default async function DrivingPage({params}:{params:Promise<{id:string}>}){const{id}=await params;const{supabase}=await requireVerifiedUser(`/trips/${id}/driving`);const[{data:trip},{data:segments},{data:rentals}]=await Promise.all([
  supabase.from("trips").select("id,title,cities,trip_days(id,trip_date,title)").eq("id",id).single(),
  supabase.from("transport_segments").select("id,day_id,mode,operator,service_name,origin,destination,departure_time,arrival_time,booking_reference,seat,notes").eq("trip_id",id).eq("mode","car").order("sort_order"),
  supabase.from("bookings").select("id,title,provider,reference_code,start_at,end_at,confirmation_url,notes,details").eq("trip_id",id).eq("booking_type","rental_car").order("start_at",{ascending:true,nullsFirst:false})
]);if(!trip)notFound();const days=new Map((trip.trip_days||[]).map((d:any)=>[d.id,d]));return <main className="shell"><div className="container"><AppHeader/><div className="planner-topbar"><Link href={`/trips/${id}/command-center`} className="back-link">‹ Command Center</Link><span className="planner-counter">V9.6 Japan Driving Assistant</span></div><section className="planner-hero driving-hero"><div><span className="eyebrow">RENTAL CAR CONTROL</span><h1>🚙 Japan Driving Assistant</h1><p>{trip.title} · รถเช่า เส้นทาง ETC Snow tire น้ำมัน ที่จอดรถ และคืนรถ</p></div><div className="master-hero-actions"><Link className="btn btn-primary" href={`/trips/${id}/transport#rental-car`}>+ เพิ่มช่วงขับรถ</Link><Link className="btn btn-secondary" href={`/trips/${id}/route-cost`}>Cost</Link></div></section>
<DrivingChecklist tripId={id}/>
<section className="section"><div className="section-head"><h2>Rental bookings</h2><Link className="link" href={`/trips/${id}/bookings`}>Booking Center ›</Link></div>{rentals?.length?<div className="driving-booking-grid">{rentals.map((b:any)=><article className="card driving-booking-card" key={b.id}><span className="activity-label">RENTAL CAR</span><h3>{b.title||b.provider||"Rental car"}</h3><p>{b.provider||""}</p>{b.reference_code&&<div className="reference-chip">Ref {b.reference_code}</div>}<div className="tag-row">{detail(b.details,"etc")&&<span className="mini-tag">ETC {detail(b.details,"etc")}</span>}{detail(b.details,"snow_tire")&&<span className="mini-tag">Snow tire {detail(b.details,"snow_tire")}</span>}{detail(b.details,"fuel_policy")&&<span className="mini-tag">Fuel {detail(b.details,"fuel_policy")}</span>}</div>{b.confirmation_url&&<a className="link" href={b.confirmation_url} target="_blank" rel="noreferrer">เปิด Confirmation ↗</a>}</article>)}</div>:<div className="empty-mini">ยังไม่มี Rental car booking ใน Booking Center</div>}</section>
<section className="section"><div className="section-head"><h2>Driving segments</h2><span className="small muted">{segments?.length||0} ช่วง</span></div>{segments?.length?<div className="route-segment-list">{segments.map((s:any,index:number)=>{const day=days.get(s.day_id) as any;return <article className="route-segment-card rental" key={s.id}><div className="route-segment-order"><span>🚙</span><b>{index+1}</b></div><div className="route-segment-main"><div className="route-segment-meta">{day?`${day.trip_date} · `:""}{s.operator||"Rental car"}</div><h3>{s.origin} <span>→</span> {s.destination}</h3><div className="route-time-row"><strong>{s.departure_time?.slice(0,5)||"—"}</strong><span>→</span><strong>{s.arrival_time?.slice(0,5)||"—"}</strong></div>{s.service_name&&<p>รถ/คลาส: {s.service_name}</p>}<div className="tag-row">{s.booking_reference&&<span className="mini-tag">Ref {s.booking_reference}</span>}{s.seat&&<span className="mini-tag">{s.seat}</span>}</div>{s.notes&&<p className="small muted">{s.notes}</p>}<div className="today-action-row"><a className="btn btn-primary btn-small" href={mapsDirectionsUrl(s.origin,s.destination,"driving")} target="_blank" rel="noreferrer">Google Maps</a><a className="btn btn-secondary btn-small" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`gas station near ${s.destination}, Japan`)}`} target="_blank" rel="noreferrer">ปั๊มน้ำมัน</a><a className="btn btn-secondary btn-small" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`parking near ${s.destination}, Japan`)}`} target="_blank" rel="noreferrer">ที่จอดรถ</a></div></div></article>})}</div>:<div className="empty-state"><div className="empty-icon">🚙</div><h2>ยังไม่มีช่วงรถเช่า</h2><p>เพิ่ม Transport mode = Rental car ก่อน</p><Link className="btn btn-primary" href={`/trips/${id}/transport#rental-car`}>เพิ่ม Rental car</Link></div>}</section>
<section className="notice"><span>⚠️</span><div><strong>ก่อนขับจริงให้ตรวจข้อมูลจากบริษัทเช่ารถและป้ายจราจรหน้างาน</strong><p>หน้าจอนี้ช่วยรวบรวมแผนและ checklist เท่านั้น ไม่แทนเงื่อนไขสัญญาเช่า กฎหมายจราจร หรือข้อมูลถนนแบบเรียลไทม์</p></div></section>
</div><BottomNav active="/plan"/></main>}
