"use server";

import { revalidatePath } from "next/cache";
import { requireVerifiedUser } from "@/lib/supabase/auth";

function arr(value:unknown){return Array.isArray(value)?value:[];}
function obj(value:unknown){return value && typeof value==='object' && !Array.isArray(value) ? value as Record<string,unknown> : {};}
function s(value:unknown){return typeof value==='string'?value:'';}
function n(value:unknown){const x=Number(value);return Number.isFinite(x)?x:null;}

export async function restoreTripBackup(payload: unknown) {
  const backup=obj(payload); const trip=obj(backup.trip); const { supabase }=await requireVerifiedUser('/trips');
  if(s(backup.format)!=='tabi-family-backup') throw new Error('ไฟล์นี้ไม่ใช่ Tabi Family backup');
  const start=s(trip.start_date), end=s(trip.end_date); if(!start||!end) throw new Error('Backup ไม่มีวันเริ่ม/สิ้นสุดทริป');
  const members=arr(backup.members).map(obj); const adults=members.filter(x=>s(x.member_type)==='adult').length; const children=members.filter(x=>s(x.member_type)==='child').length; const seniors=members.filter(x=>s(x.member_type)==='senior').length;
  const { data:tripId,error:createError }=await supabase.rpc('create_trip_bundle',{p_title:`${s(trip.title)||'Restored Trip'} · Restore`,p_start_date:start,p_end_date:end,p_cities:arr(trip.cities).map(String),p_pace:s(trip.pace)||'balanced',p_budget:n(trip.budget),p_adults:adults,p_children:children,p_seniors:seniors});
  if(createError||!tripId) throw new Error(`สร้าง Trip สำหรับ Restore ไม่สำเร็จ: ${createError?.message||'unknown error'}`);
  const id=String(tripId);

  // Replace generated member placeholders with backed-up profiles.
  await supabase.from('trip_members').delete().eq('trip_id',id);
  if(members.length){const rows=members.map(m=>({trip_id:id,name:s(m.name)||'Member',member_type:s(m.member_type)||'adult',age:n(m.age),walking_level:n(m.walking_level)||3,needs:arr(m.needs),dietary_preferences:arr(m.dietary_preferences),interests:arr(m.interests),mobility_notes:s(m.mobility_notes)||null,avoid_stairs:Boolean(m.avoid_stairs),needs_frequent_rest:Boolean(m.needs_frequent_rest),stroller:Boolean(m.stroller),notes:s(m.notes)||null,passport_expiry:s(m.passport_expiry)||null,seat_preference:s(m.seat_preference)||null,rail_pass:s(m.rail_pass)||null,child_seat:Boolean(m.child_seat),booster_seat:Boolean(m.booster_seat),emergency_contact:s(m.emergency_contact)||null,document_note:s(m.document_note)||null})); const {error}=await supabase.from('trip_members').insert(rows); if(error) throw new Error(`Restore สมาชิกไม่สำเร็จ: ${error.message}`);}

  const {data:newDays}=await supabase.from('trip_days').select('id,trip_date').eq('trip_id',id); const dayMap=new Map((newDays||[]).map((d:any)=>[d.trip_date,d.id]));
  for(const oldDay0 of arr(backup.days)){const oldDay=obj(oldDay0); const dayId=dayMap.get(s(oldDay.trip_date)); if(!dayId) continue; await supabase.from('trip_days').update({title:s(oldDay.title)||null,notes:s(oldDay.notes)||null}).eq('id',dayId); const activities=arr(oldDay.activities).map(obj).map((a,index)=>({day_id:dayId,title:s(a.title)||'Activity',activity_type:s(a.activity_type)||'attraction',start_time:s(a.start_time)||null,duration_minutes:n(a.duration_minutes),location_name:s(a.location_name)||null,latitude:n(a.latitude),longitude:n(a.longitude),reservation_required:Boolean(a.reservation_required),child_friendly:a.child_friendly!==false,senior_friendly:a.senior_friendly!==false,sort_order:n(a.sort_order)??index,notes:s(a.notes)||null,place_id:s(a.place_id)||null,status:s(a.status)||'planned',is_outdoor:Boolean(a.is_outdoor),rain_alternative:s(a.rain_alternative)||null,maps_url:s(a.maps_url)||null})); if(activities.length){const {error}=await supabase.from('activities').insert(activities); if(error) throw new Error(`Restore activities ไม่สำเร็จ: ${error.message}`);}}

  const bookings=arr(backup.bookings).map(obj).filter(b=>s(b.booking_type)!=='document').map(b=>({trip_id:id,booking_type:s(b.booking_type)||'other',title:s(b.title)||null,provider:s(b.provider)||null,reference_code:s(b.reference_code)||null,start_at:s(b.start_at)||null,end_at:s(b.end_at)||null,confirmation_url:s(b.confirmation_url)||null,notes:s(b.notes)||null,details:{...obj(b.details),restored_from_backup:true}})); if(bookings.length){const {error}=await supabase.from('bookings').insert(bookings); if(error) throw new Error(`Restore bookings ไม่สำเร็จ: ${error.message}`);}
  const expenses=arr(backup.expenses).map(obj).map(e=>({trip_id:id,category:s(e.category)||'other',amount:n(e.amount)||0,currency:s(e.currency)||'JPY',paid_at:s(e.paid_at)||new Date().toISOString(),note:s(e.note)||null,paid_by:s(e.paid_by)||null,payment_method:s(e.payment_method)||null,exchange_rate_thb:n(e.exchange_rate_thb),planned_amount:n(e.planned_amount)})); if(expenses.length){const {error}=await supabase.from('expenses').insert(expenses); if(error) throw new Error(`Restore expenses ไม่สำเร็จ: ${error.message}`);}
  const packing=arr(backup.packing).map(obj).map((x,index)=>({trip_id:id,label:s(x.label)||'Item',category:s(x.category)||'other',assigned_to:s(x.assigned_to)||null,quantity:n(x.quantity)||1,is_packed:Boolean(x.is_packed),notes:s(x.notes)||null,sort_order:n(x.sort_order)??index})); if(packing.length){const {error}=await supabase.from('packing_items').insert(packing); if(error) throw new Error(`Restore packing ไม่สำเร็จ: ${error.message}`);}
  const wishlist=arr(backup.wishlist).map(obj).map(w=>({trip_id:id,place_key:s(w.place_key)||crypto.randomUUID(),title:s(w.title)||'Place',city:s(w.city)||null,category:s(w.category)||'attraction',emoji:s(w.emoji)||null,summary:s(w.summary)||null,maps_url:s(w.maps_url)||null,latitude:n(w.latitude),longitude:n(w.longitude),child_friendly:w.child_friendly!==false,senior_friendly:w.senior_friendly!==false,is_outdoor:Boolean(w.is_outdoor),duration_minutes:n(w.duration_minutes),notes:s(w.notes)||null})); if(wishlist.length){const {error}=await supabase.from('trip_wishlist').insert(wishlist); if(error) throw new Error(`Restore wishlist ไม่สำเร็จ: ${error.message}`);}
  const transport=arr(backup.transport).map(obj).map((t,index)=>({trip_id:id,day_id:dayMap.get(s(t.trip_date))||null,mode:s(t.mode)||'other',operator:s(t.operator)||null,service_name:s(t.service_name)||null,origin:s(t.origin)||'Origin',destination:s(t.destination)||'Destination',departure_time:s(t.departure_time)||null,arrival_time:s(t.arrival_time)||null,reservation_required:Boolean(t.reservation_required),booking_reference:s(t.booking_reference)||null,seat:s(t.seat)||null,notes:s(t.notes)||null,sort_order:n(t.sort_order)??index,distance_km:n(t.distance_km),toll_jpy:n(t.toll_jpy),fuel_jpy:n(t.fuel_jpy),parking_jpy:n(t.parking_jpy),rest_stop:s(t.rest_stop)||null,winter_ready:Boolean(t.winter_ready)})); if(transport.length){const {error}=await supabase.from('transport_segments').insert(transport); if(error) throw new Error(`Restore transport ไม่สำเร็จ: ${error.message}`);}
  revalidatePath('/trips'); revalidatePath(`/trips/${id}`); return {tripId:id, skippedDocuments:Number(backup.documentCount||0)};
}
