import Link from "next/link";
import { notFound } from "next/navigation";
import { AppHeader } from "@/components/AppHeader";
import { BottomNav } from "@/components/BottomNav";
import { TripBackupRestore } from "@/components/TripBackupRestore";
import { requireVerifiedUser } from "@/lib/supabase/auth";

export default async function BackupPage({params}:{params:Promise<{id:string}>}){const{id}=await params;const{supabase}=await requireVerifiedUser(`/trips/${id}/backup`);const[{data:trip},{data:transport},{count:documentCount}]=await Promise.all([
 supabase.from('trips').select(`id,title,start_date,end_date,cities,pace,budget,currency,trip_members(*),trip_days(id,trip_date,title,notes,activities(*)),bookings(*),expenses(*),packing_items(*),trip_wishlist(*)`).eq('id',id).single(),
 supabase.from('transport_segments').select('*').eq('trip_id',id).order('sort_order'),
 supabase.from('bookings').select('id',{count:'exact',head:true}).eq('trip_id',id).eq('booking_type','document')
]);if(!trip)notFound();const days=[...(trip.trip_days||[])].sort((a:any,b:any)=>a.trip_date.localeCompare(b.trip_date));const dayDate=new Map(days.map((d:any)=>[d.id,d.trip_date]));const backup={format:'tabi-family-backup',schemaVersion:'11.2',exportedAt:new Date().toISOString(),trip:{id:trip.id,title:trip.title,start_date:trip.start_date,end_date:trip.end_date,cities:trip.cities,pace:trip.pace,budget:trip.budget,currency:trip.currency},members:trip.trip_members||[],days,bookings:(trip.bookings||[]).filter((b:any)=>b.booking_type!=='document'),expenses:trip.expenses||[],packing:trip.packing_items||[],wishlist:trip.trip_wishlist||[],transport:(transport||[]).map((t:any)=>({...t,trip_date:t.day_id?dayDate.get(t.day_id)||null:null})),documentCount:documentCount||0};return <main className="shell"><div className="container"><AppHeader/><div className="planner-topbar"><Link className="back-link" href={`/trips/${id}/more`}>‹ More</Link><span className="planner-counter">V10.7 Backup / Restore</span></div><section className="planner-hero"><div><span className="eyebrow">DATA PORTABILITY</span><h1>💾 Backup & Restore</h1><p>{trip.title} · สำรองข้อมูลก่อนแก้แผนใหญ่หรือก่อนเดินทาง</p></div></section><TripBackupRestore backup={backup}/><section className="notice"><span>🔐</span><div><strong>Private documents ไม่ถูกฝังใน JSON</strong><p>Backup นี้เก็บข้อมูลโครงสร้างและ document count เท่านั้น ไฟล์จริงยังอยู่ใน Supabase Storage ของ Trip เดิม</p></div></section></div><BottomNav active="/more" tripId={id} /></main>}
